# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master, gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cancer-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.1'

      - name: Install dependencies
        run: |
          sudo apt -y install libcurl4-openssl-dev
          Rscript install_packages.R

      # Runs a single command using the runners shell
      - name: Run the skin-cancer scripts
        run: |
          Rscript Skin_Cancer_Analysis.R
